/** Plain note text is escaped here; callers never supply Graph HTML. */
export interface MentionMessage {
  text: string;
  pageTitle: string;
  origin: string;
  sourcePath: string;
}

const MAX_MESSAGE_BYTES = 24_000;
const utf8Bytes = (value: string) => new TextEncoder().encode(value).length;
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, char => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[char]!));
const cleanText = (value: string) => value.replace(/\r\n?/g, '\n').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, '');

export function renderMentionMessage(input: MentionMessage): string | null {
  if (typeof input.text !== 'string' || !input.text.trim() || Array.from(input.text).length > 4000
    || typeof input.pageTitle !== 'string' || typeof input.origin !== 'string'
    || typeof input.sourcePath !== 'string' || input.sourcePath.length > 6000) return null;
  let href: string;
  try {
    const origin = new URL(input.origin);
    if (origin.username || origin.password || origin.pathname !== '/' || origin.search || origin.hash
      || (origin.protocol !== 'https:' && !(process.env.NODE_ENV !== 'production'
        && origin.protocol === 'http:' && origin.hostname === 'localhost'))) return null;
    // Only internal routes generated by the source resolver, never a caller URL.
    if (!/^\/(?:product|ranking|brand|company)(?:\?|$)/.test(input.sourcePath)
      && !/^\/me\/notes\/[0-9a-f-]{36}$/i.test(input.sourcePath)) return null;
    if (/[\r\n\\]/.test(input.sourcePath)) return null;
    const source = new URL(input.sourcePath, origin);
    if (source.origin !== origin.origin || source.username || source.password || source.hash) return null;
    href = source.toString();
  } catch { return null; }
  const titleChars = Array.from(cleanText(input.pageTitle).replace(/\s+/g, ' ').trim() || '메모');
  const title = titleChars.length > 120 ? titleChars.slice(0, 119).join('') + '…' : titleChars.join('');
  const prefix = `<p>[UTTU] ${escapeHtml(title)}에서 회원님을 멘션했습니다.</p><p>`;
  const suffix = `</p><p><a href="${escapeHtml(href)}">UTTU에서 메모 보기 ↗</a></p>`;
  const budget = MAX_MESSAGE_BYTES - utf8Bytes(prefix + suffix + '…');
  if (budget < 0) return null;
  let body = '';
  let bytes = 0;
  // Bound the encoded HTML, not just raw character count. Keep entities and
  // Unicode code points whole when an unusually escape-heavy note is shortened.
  for (const char of cleanText(input.text)) {
    const encoded = char === '\n' ? '<br>' : escapeHtml(char);
    const length = utf8Bytes(encoded);
    if (bytes + length > budget) { body += '…'; break; }
    body += encoded;
    bytes += length;
  }
  return prefix + body + suffix;
}
