const test=require('node:test'),assert=require('node:assert/strict'),React=require('react'),Renderer=require('react-test-renderer'),load=require('./helpers/load-source.cjs');
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const act=fn=>React.act(fn),flat=n=>typeof n==='string'?n:Array.isArray(n)?n.map(flat).join(''):n?.children?.map(flat).join('')??'',text=r=>flat(r.toJSON()),button=(r,label)=>r.root.findAllByType('button').find(b=>b.children.join('')===label);
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const article=(title='saved magazine',id='one')=>({id,article_id:id,cms_index:null,title,category:'style',sub_category:null,brand_names:[],view_count:12,comment_count:2,published_at:'2026-10-05',collected_at:'2026-10-05',thumbnail_url:null,summary:'<script>escaped text</script>',landing_url:'https://www.musinsa.com/app/contents/detail/'+id});
const response=(rows=[article()],count=rows.length)=>({data:rows,count,error:null});
function fixture(mobile=false){
 let owner='owner',params='',timerId=0;const plans=[],calls=[],listeners=new Set(),timers=new Map(),saved={setTimeout:global.setTimeout,clearTimeout:global.clearTimeout,fetch:global.fetch};
 global.fetch=()=>assert.fail('No live network');global.setTimeout=(fn,delay)=>{timers.set(++timerId,{fn,delay});return timerId;};global.clearTimeout=id=>timers.delete(id);
 const sdk={auth:{getUser:async()=>({data:{user:owner?{id:owner}:null},error:null}),onAuthStateChange(fn){listeners.add(fn);return {data:{subscription:{unsubscribe(){listeners.delete(fn);}}}};}},from(table){const call={kind:table,filters:{}};const q={select(cols){if(table==='magazine_articles')call.kind=cols==='category'?'categories':'articles';return q;},eq(k,v){call.filters[k]=v;return q;},ilike(k,v){call.filters[k]=v;return q;},gte(k,v){call.filters.from=v;return q;},lte(k,v){call.filters.to=v;return q;},not(){return q;},in(){return q;},order(k){call.sort=k;return q;},range(from,to){call.from=from;call.to=to;return q;},limit(){return q;},abortSignal(signal){call.signal=signal;return q;},insert(){assert.fail('No writes');},upsert(){assert.fail('No writes');},then(a,b){calls.push(call);const index=plans.findIndex(p=>p.kind===call.kind),p=index<0?null:plans.splice(index,1)[0];return Promise.resolve(p?p.value:call.kind==='articles'?response():call.kind==='categories'?response([{category:'style'},{category:'trend'}]):response([])).then(a,b);}};return q;}};
 const client={supabaseBrowser:()=>sdk},mocks={'@/lib/supabase/client':client,'./supabase/client':client,'next/navigation':{useSearchParams:()=>new URLSearchParams(params),useRouter:()=>({push(){assert.fail('No real navigation');},back(){}})},'next/link':({children,...props})=>React.createElement('a',props,children),'@/hooks/useViewport':{useIsMobile:()=>mobile},'@/components/me/NoteDrawer':()=>null};
 const Page=load('src/app/(app)/magazine/page.tsx',mocks).default;
 return {Page,mocks,calls,timers,listeners,plan:(kind,value)=>plans.push({kind,value}),route:p=>{params=p;},auth:id=>{owner=id;for(const fn of listeners)fn(id?'SIGNED_IN':'SIGNED_OUT',id?{user:{id}}:null);},async expire(){const entry=[...timers].find(([,v])=>v.delay===15000);assert.ok(entry);timers.delete(entry[0]);await act(async()=>entry[1].fn());},restore(){Object.assign(global,saved);}};
}
for(const mobile of [false,true]){
 const label=mobile?'mobile':'desktop';
 test(label+' initial failure is distinct from absence; retry single-flight and last-good same scope',async()=>{const f=fixture(mobile);let root;try{
 f.plan('articles',{data:null,count:null,error:{code:'403'}});await act(async()=>{root=Renderer.create(React.createElement(f.Page));});assert.match(text(root),/매거진 조회에 실패/);assert.doesNotMatch(text(root),/데이터가 없습니다|0건 수집/);
 const old=deferred();f.plan('articles',old.promise);const control=button(root,'매거진 다시 조회');await act(async()=>{control.props.onClick();control.props.onClick();});assert.equal(f.calls.filter(c=>c.kind==='articles').length,2);assert.equal(button(root,'매거진 다시 조회'),control);assert.equal(control.props['aria-disabled'],true);
 await act(async()=>old.resolve(response()));assert.match(text(root),/saved magazine/);f.plan('articles',Promise.reject(Error('offline')));await act(async()=>control.props.onClick());assert.match(text(root),/이전에 조회한 같은 조회 조건/);assert.match(text(root),/saved magazine/);
 f.plan('articles',response([]));await act(async()=>control.props.onClick());assert.match(text(root),/매거진 데이터가 없습니다/);assert.doesNotMatch(text(root),/saved magazine/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);assert.equal(f.listeners.size,0);f.restore();}});
 test(label+' filter epochs mask late success/error/finally, return-to-filter and owner/signed-out data',async()=>{const f=fixture(mobile);let root;try{
 const old=deferred();f.plan('articles',old.promise);await act(async()=>{root=Renderer.create(React.createElement(f.Page));});const previous=f.calls.find(c=>c.kind==='articles');const next=deferred();f.plan('articles',next.promise);
 await act(async()=>button(root,mobile?'트렌드':'trend').props.onClick(mobile?'trend':undefined));assert.equal(previous.signal.aborted,true);await act(async()=>old.resolve(response([article('obsolete')])));assert.doesNotMatch(text(root),/obsolete/);assert.equal(button(root,'매거진 다시 조회').props['aria-disabled'],true);
 await act(async()=>next.resolve(response([article('trend data')])));assert.match(text(root),/trend data/);const late=deferred();f.plan('articles',late.promise);await act(async()=>button(root,'매거진 다시 조회').props.onClick());f.plan('articles',{data:null,error:{code:'500'}});await act(async()=>button(root,'전체').props.onClick(mobile?'':undefined));assert.doesNotMatch(text(root),/trend data|saved magazine/);await act(async()=>late.reject(Error('obsolete failure')));assert.match(text(root),/매거진 조회에 실패/);
 await act(async()=>button(root,'매거진 다시 조회').props.onClick());const ownerRead=deferred();f.plan('articles',ownerRead.promise);await act(async()=>f.auth('replacement'));assert.doesNotMatch(text(root),/saved magazine/);await act(async()=>ownerRead.resolve(response([article('new owner')])));assert.match(text(root),/new owner/);await act(async()=>f.auth(null));assert.match(text(root),/로그인 후 매거진/);assert.doesNotMatch(text(root),/new owner|0건 수집/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
 test(label+' timeout/retry rejects obsolete result and unmount clears timers',async()=>{const f=fixture(mobile),old=deferred(),fresh=deferred();let root;try{
 f.plan('articles',old.promise);await act(async()=>{root=Renderer.create(React.createElement(f.Page));});await f.expire();assert.match(text(root),/조회 시간이 초과/);assert.equal(f.calls.find(c=>c.kind==='articles').signal.aborted,true);f.plan('articles',fresh.promise);await act(async()=>button(root,'매거진 다시 조회').props.onClick());await act(async()=>old.resolve(response([article('obsolete timeout')])));assert.doesNotMatch(text(root),/obsolete timeout/);await act(async()=>fresh.resolve(response()));assert.match(text(root),/saved magazine/);
 const dispose=deferred();f.plan('articles',dispose.promise);await act(async()=>button(root,'매거진 다시 조회').props.onClick());await act(async()=>root.unmount());root=null;assert.equal(f.timers.size,0);assert.equal(f.calls.filter(c=>c.kind==='articles').at(-1).signal.aborted,true);await act(async()=>dispose.reject(Error('late dispose')));
 }finally{await act(async()=>root?.unmount());f.restore();}});
 test(label+' expanded stale article is labelled; query changes hide sheet and old detail',async()=>{const f=fixture(mobile);let root;try{
 const detail=deferred();f.plan('magazine_article_products',detail.promise);await act(async()=>{root=Renderer.create(React.createElement(f.Page));});const row=root.root.findAll(n=>n.props.onClick&&n.children?.some(c=>typeof c==='object'&&c?.type==='span')&&n.props.className?.includes('row hover'))[0]??root.root.findAll(n=>n.props.role==='button')[0];await act(async()=>row.props.onClick());assert.match(text(root),/매거진 상세를 불러오는 중/);
 f.plan('articles',{data:null,error:{code:'500'}});await act(async()=>button(root,'매거진 다시 조회').props.onClick());assert.match(text(root),/이전에 조회한 같은 조회 조건의 기사/);await act(async()=>button(root,mobile?'트렌드':'trend').props.onClick(mobile?'trend':undefined));assert.doesNotMatch(text(root),/매거진 상세/);await act(async()=>detail.resolve(response([{musinsa_no:'1',product_id:'1',products:{name:'obsolete product'}}])));assert.doesNotMatch(text(root),/obsolete product/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
}
test('mobile linked-product count distinguishes loading, failure, timeout, genuine zero, success and stale refresh',async()=>{const f=fixture(true);let root;try{
 f.plan('magazine_article_products',{data:null,error:{code:'500'}});await act(async()=>{root=Renderer.create(React.createElement(f.Page));});await act(async()=>root.root.findAll(n=>n.props.role==='button')[0].props.onClick());assert.match(text(root),/연결 상품 확인 불가/);assert.doesNotMatch(text(root),/연결 상품 0개/);
 const pending=deferred();f.plan('magazine_article_products',pending.promise);await act(async()=>button(root,'매거진 상세 다시 조회').props.onClick());assert.match(text(root),/연결 상품 확인 중/);assert.doesNotMatch(text(root),/연결 상품 0개/);await f.expire();assert.match(text(root),/조회 시간이 초과/);assert.match(text(root),/연결 상품 확인 불가/);assert.doesNotMatch(text(root),/연결 상품 0개/);
 f.plan('magazine_article_products',response([]));await act(async()=>button(root,'매거진 상세 다시 조회').props.onClick());assert.match(text(root),/연결 상품 0개/);assert.doesNotMatch(text(root),/연결 상품 0개 \(이전 조회\)/);
 f.plan('magazine_article_products',response([{musinsa_no:'123',product_id:'product',products:{name:'saved product',is_own:false,brands:{name:'brand'}}}]));await act(async()=>button(root,'매거진 상세 다시 조회').props.onClick());assert.match(text(root),/연결 상품 1개/);assert.doesNotMatch(text(root),/연결 상품 1개 \(이전 조회\)/);
 f.plan('magazine_article_products',{data:null,error:{code:'500'}});await act(async()=>button(root,'매거진 상세 다시 조회').props.onClick());assert.match(text(root),/연결 상품 1개 \(이전 조회\)/);assert.match(text(root),/saved product/);await act(async()=>pending.resolve(response([{musinsa_no:'late',products:{name:'late product'}}])));assert.doesNotMatch(text(root),/late product/);
 const refresh=deferred();f.plan('magazine_article_products',refresh.promise);await act(async()=>button(root,'매거진 상세 다시 조회').props.onClick());assert.match(text(root),/연결 상품 1개 \(이전 조회\)/);await act(async()=>refresh.resolve(response([])));assert.match(text(root),/연결 상품 0개/);assert.doesNotMatch(text(root),/연결 상품 0개 \(이전 조회\)/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
test('desktop page controls survive pending/rejected Next; categories are owner-scoped with retry/back recovery',async()=>{const f=fixture();let root;try{
 f.plan('articles',response([article()],75));await act(async()=>{root=Renderer.create(React.createElement(f.Page));});const categories=f.calls.filter(c=>c.kind==='categories').length;const next=root.root.findAllByType('button').find(b=>b.props['aria-label']==='다음 페이지'),prev=root.root.findAllByType('button').find(b=>b.props['aria-label']==='이전 페이지');const pending=deferred();f.plan('articles',pending.promise);await act(async()=>next.props.onClick());assert.equal(root.root.findAllByType('button').find(b=>b.props['aria-label']==='다음 페이지'),next);assert.equal(next.props['aria-disabled'],true);assert.equal(prev.props['aria-disabled'],false);assert.match(text(root),/2 \/ \?|전체 건수 확인 중/);assert.doesNotMatch(text(root),/75|saved magazine/);assert.equal(f.calls.filter(c=>c.kind==='categories').length,categories);
 await act(async()=>pending.reject(Error('page unavailable')));assert.equal(root.root.findAllByType('button').find(b=>b.props['aria-label']==='다음 페이지'),next);assert.match(text(root),/전체 건수 확인 불가/);assert.equal(prev.props['aria-disabled'],false);f.plan('articles',response([article('page two')],75));await act(async()=>button(root,'매거진 다시 조회').props.onClick());assert.match(text(root),/page two|51–75/);f.plan('articles',response([article('back page')],75));await act(async()=>prev.props.onClick());assert.match(text(root),/back page/);
 const option=button(root,'trend');f.plan('articles',{data:null,error:{code:'500'}});await act(async()=>option.props.onClick());assert.equal(button(root,'trend'),option);assert.equal(f.calls.filter(c=>c.kind==='categories').length,categories);assert.doesNotMatch(text(root),/back page|75/);await act(async()=>button(root,'매거진 다시 조회').props.onClick());assert.match(text(root),/saved magazine/);assert.equal(f.calls.filter(c=>c.kind==='categories').length,categories);
 await act(async()=>f.auth('replacement'));assert.equal(f.calls.filter(c=>c.kind==='categories').length,categories+1);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
test('desktop pagination and query id epochs mask late old page and jump detail',async()=>{const f=fixture();let root;try{
 f.plan('articles',response([article()],75));await act(async()=>{root=Renderer.create(React.createElement(f.Page));});const old=deferred();f.plan('articles',old.promise);await act(async()=>root.root.findAllByType('button').filter(b=>b.props.className==='btn sm icon').at(-1).props.onClick());assert.equal(f.calls.filter(c=>c.kind==='articles').at(-1).from,50);assert.doesNotMatch(text(root),/saved magazine/);
 f.plan('articles',response([article('query article','two')],75));f.route('id=two');await act(async()=>root.update(React.createElement(f.Page)));assert.match(text(root),/매거진 상세/);await act(async()=>old.resolve(response([article('obsolete page')],75)));assert.doesNotMatch(text(root),/obsolete page/);f.route('id=missing');await act(async()=>root.update(React.createElement(f.Page)));assert.doesNotMatch(text(root),/매거진 상세|query article/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
test('desktop selected article follows its id on reorder and closes when absent',async()=>{const f=fixture();let root;try{
 f.plan('articles',response([article('first','one'),article('second','two')]));await act(async()=>{root=Renderer.create(React.createElement(f.Page));});await act(async()=>root.root.findAll(n=>n.props.className?.startsWith('row hover'))[1].props.onClick());let aside=root.root.findByType('aside');assert.match(flat(aside.toJSON?.()??{children:aside.children.map(n=>typeof n==='string'?n:{children:n.children})}),/second/);
 f.plan('articles',response([article('second','two'),article('first','one')]));await act(async()=>button(root,'매거진 다시 조회').props.onClick());assert.ok(root.root.findByType('aside').findAllByType('h3').some(n=>n.children.join('')==='second'));
 f.plan('articles',response([article('first','one')]));await act(async()=>button(root,'매거진 다시 조회').props.onClick());assert.equal(root.root.findAllByType('aside').length,0);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
test('mobile incomplete/reversed custom range masks previous results without a read',async()=>{const f=fixture(true);let root;try{
 await act(async()=>{root=Renderer.create(React.createElement(f.Page));});const count=f.calls.filter(c=>c.kind==='articles').length;await act(async()=>button(root,'직접선택').props.onClick());assert.doesNotMatch(text(root),/saved magazine|데이터가 없습니다/);assert.match(text(root),/시작일과 종료일/);const inputs=root.root.findAllByType('input');await act(async()=>{inputs[0].props.onChange({target:{value:'2026-10-05'}});inputs[1].props.onChange({target:{value:'2026-10-01'}});});assert.equal(f.calls.filter(c=>c.kind==='articles').length,count);assert.match(text(root),/시작일과 종료일/);
 }finally{await act(async()=>root?.unmount());assert.equal(f.timers.size,0);f.restore();}});
test('actual reader filters/page/count/SDK failures and malformed payloads',async()=>{const f=fixture(),q=load('src/lib/queries.ts',f.mocks);try{
 const signal=new AbortController().signal;await q.fetchMagazineArticles({category:'trend',keyword:'brand',dateFrom:'2026-10-01',dateTo:'2026-10-05',sort:'view_count',offset:50,limit:50,signal});const call=f.calls.at(-1);assert.equal(call.from,50);assert.equal(call.to,99);assert.equal(call.sort,'view_count');assert.equal(call.filters.title,'%brand%');assert.equal(call.filters.to,'2026-10-05T23:59:59');assert.equal(call.signal,signal);
 for(const value of [{data:null,count:0,error:null},response([],null),response([],-1),response([{...article(),brand_names:null}]),response([{...article(),title:null}]),{data:[],count:0,error:{code:'500'}}]){f.plan('articles',value);await assert.rejects(q.fetchMagazineArticles({}));}f.plan('articles',response([]));assert.deepEqual(await q.fetchMagazineArticles({}),{rows:[],total:0});
 for(const [kind,read]of [['categories',()=>q.fetchMagazineCategories()],['magazine_article_products',()=>q.fetchMagazineProducts('one')],['anomalies',()=>q.fetchMagazineBoostAnomalies({})]]){f.plan(kind,{data:null,count:null,error:{code:'500'}});await assert.rejects(read());}
 }finally{f.restore();}});
test('source URLs preserve HTTP(S) originals and reject executable, malformed and credential-bearing destinations',()=>{const {magazineSourceUrl:valid,mobileMagazineSourceUrl:mobile}=load('src/lib/magazine-source.ts');for(const url of ['https://www.musinsa.com/app/contents/detail/123','http://another.publisher.example/a?x=1#section','HTTPS://Example.com:8443/한글?a=%20','https://example.com/?redirect=javascript%3Afoo'])assert.equal(valid(url),url);for(const url of [null,undefined,'','/relative','//example.com','javascript:alert(1)','data:text/html,x','file:///tmp/x','mailto:a@b','https://a:b@example.com','https://user@example.com','https://%75ser@example.com',' https://example.com','https://example.com/a b','https://example.com\n','https://example.com\\other','https://[bad','https://'])assert.equal(valid(url),null,String(url));assert.equal(mobile(null,'123'),'https://www.musinsa.com/app/contents/detail/123');assert.equal(mobile('javascript:alert(1)','123'),null);assert.equal(mobile('', '123'),null);});
