// Shell + route integration extension: actual ShellClient/MobileShell source, inert chrome/service boundaries.
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict');
const fixturePath=path.join(__dirname,'performance-viewport.test.cjs');
let source=fs.readFileSync(fixturePath,'utf8').split('\n(async()=>{')[0];
source=source.replace("const { readSource } = require('./performance-source.cjs');", "const { readSource: readBaseSource } = require('./performance-source.cjs');\nfunction readSource(ref){const name=ref.split('/')[1];if(['ShellClient.tsx','MobileShell.tsx'].includes(name))return fs.readFileSync(require('node:path').join(__dirname,'../src/components/shell',name),'utf8');return readBaseSource(ref)}");
source=source.replace("'next/navigation':{useRouter:","'next/navigation':{usePathname:()=>'/'+route,useRouter:");
source=source.replace("const modules={", "const modules={'@/components/briefing/CSDailyReviewBoundary':{__esModule:true,default:({children})=>children},'@/components/report/DailyReportBoundary':{__esModule:true,default:({children})=>children},'@/components/onboarding/OnboardingProvider':{useOnboarding:()=>({active:false,step:0})},'@/lib/supabase/client':{supabaseBrowser:()=>({auth:{getUser:async()=>({data:{user:null}})}})},");
source=source.replace("fetchNoteCountForEntity:async()=>0,logView:()=>{}", "fetchNoteCountForEntity:async()=>0,fetchUnreadCount:async()=>0,logView:()=>{}");
source=source.replace("const paths={", "const paths={'./MobileShell':'current/MobileShell.tsx',");
source=source.replace("if(typeof t[k]!=='function')return t[k];", "if(k==='fetchShellStats')return async()=>({anomalyCount:0,reviewTotal:0,reviewAvgRating:0,reviewLowCount:0,snapNew7d:0,magazineNew7d:0,promoActiveCount:0});if(typeof t[k]!=='function')return t[k];");
source=source.replace("if(id.startsWith('@/components/')", "if(['./Sidebar','./Topbar','./AiPanel','./CmdK','../help/HelpButton','../ui/icons','../me/InboxList'].includes(id)||id.startsWith('@/components/')");
source=source.replace("setTimeout,clearTimeout,CustomEvent:", "setTimeout,clearTimeout,setInterval:()=>0,clearInterval:()=>{},CustomEvent:");
source=source.replace("return{page,helpers,", "const Shell=load('current/ShellClient.tsx').default;const Route=page;function ShellRoute(){return React.createElement(Shell,null,React.createElement(Route))};return{page:ShellRoute,helpers,");
assert.ok(source.includes("const Shell=load('current/ShellClient.tsx').default"), 'Shell wrapping transformation must apply');
assert.ok(source.includes('function ShellRoute(){return React.createElement(Shell,null,React.createElement(Route))}'), 'Real shell wrapper must be present');
const mod=new Module(fixturePath,module);mod.filename=fixturePath;mod.paths=Module._nodeModulePaths(path.dirname(fixturePath));mod._compile(source+'\nmodule.exports={createFixture,mount,unmount,flush,React,Renderer};',fixturePath);
const{createFixture,mount,unmount,React}=mod.exports;
(async()=>{const results=[];for(const route of ['ranking','reviews'])for(const mobile of [false,true])for(const variant of ['source','viewport-candidate']){const f=createFixture(variant,mobile,route);const root=await mount(f);assert.equal(root.root.findAll(x=>x.type?.name==='ShellClient').length,1,'Actual ShellClient must be mounted');assert.equal(root.root.findAll(x=>x.type?.name==='MobileShell').length,mobile?1:0,'Responsive real MobileShell branch');assert.equal(f.listeners.size,2,'One shell and one route media listener');const expectedRanking=route==='ranking'?(mobile?(variant==='source'?185:3):91):0;const expectedTotal=route==='ranking'?(mobile?(variant==='source'?189:3):93):(mobile?(variant==='source'?18:2):8);assert.equal(f.rankingRequests(),expectedRanking);assert.equal(f.requests.length,expectedTotal+(mobile?1:0));results.push({route,mobile,variant,rankingQueryDispatches:f.rankingRequests(),queryDispatches:f.requests.length,helpers:f.helpers.map(x=>x.name),liveMediaListeners:f.listeners.size});if(variant==='viewport-candidate'&&mobile){assert.equal(f.rankingRequests(),route==='ranking'?3:0);assert.deepEqual(f.helpers.map(x=>x.name),route==='ranking'?['fetchLatestRanking']:['fetchOwnBrands','fetchReviews']);}await unmount(root);assert.equal(f.listeners.size,0);}console.log(JSON.stringify({react:React.version,classification:'Real ShellClient/MobileShell and route components under inert chrome, service, onboarding-context boundaries. No browser/full-app/network proof.',passed:results.length,results},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
