const test=require('node:test'),assert=require('node:assert/strict');
const React=require('react'),Renderer=require('react-test-renderer'),load=require('./helpers/load-source.cjs');
const weekly=require('./fixtures/product-history-weekly.json');
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const parse=load('src/lib/product-history-window.ts').parseProductHistoryReceipt;
test('actual SQL weekly receipt has shared chronological bins and latest partial October6 rank2',()=>{
 const h=parse(weekly);assert.equal(h.rank.at(-1).date,'2026-10-06');assert.equal(h.rank.at(-1).rank,2);assert.equal(h.price.at(-1).price,50000);assert.deepEqual(h.rank.map(p=>p.date),h.price.map(p=>p.date));assert.equal(h.rank.coverage.latestPartialWeek,true);assert.equal(h.rank.coverage.mode,'weekly');
});
test('null prices preserve bins and malformed receipts never become healthy empty',()=>{
 const r=structuredClone(weekly);r.points[1].price=null;const h=parse(r);assert.equal(h.price[1].price,null);assert.equal(h.rank.coverage.missingPrices,1);assert.deepEqual(h.rank.map(p=>p.date),h.price.map(p=>p.date));
 for(const bad of [null,{}, {...r,eligibleRows:null},{...r,threshold:501},{...r,mode:'daily'},{...r,latestDate:'2026-09-01'}, {...r,points:r.points.slice().reverse()},{...r,horizonStart:'2024-01-01'}])assert.throws(()=>parse(bad));
});
test('empty is accepted only with a coherent zero-count server receipt',()=>{
 const r={...weekly,mode:'daily',eligibleRows:0,latestDate:null,points:[]};assert.equal(parse(r).rank.length,0);assert.throws(()=>parse({...r,eligibleRows:1}));
});
test('actual reader uses one authenticated RPC and no raw-history fallback',async()=>{
 const calls=[],client={from(){throw Error('raw history forbidden');},rpc:async(name,args)=>{calls.push({name,args});return {data:weekly,error:null};}};
 const q=load('src/lib/queries.ts',{'./supabase/client':{supabaseBrowser:()=>client}});await q.fetchProductHistories('123');assert.deepEqual(calls,[{name:'get_product_history_v1',args:{p_musinsa_no:'123',p_store_code:'musinsa'}}]);await assert.rejects(()=>q.fetchProductHistories('123x'));client.rpc=async()=>({data:null,error:{code:'42883'}});await assert.rejects(()=>q.fetchProductHistories('123'));
});
for(const mobile of [false,true])test((mobile?'mobile':'desktop')+' retains product on history failure, retries only history, clears stale bins and rejects late A result',async()=>{
 const saved={window:global.window,document:global.document,fetch:global.fetch};global.window={matchMedia:()=>({matches:mobile,addEventListener(){},removeEventListener(){}}),dispatchEvent(){}};global.document={activeElement:null};global.fetch=()=>{throw Error('network forbidden');};
 let no='123',mode='fail',calls=[],resolveA;const queries={CATEGORY_MAP:{},AGE_MAP:{},fetchProductDetail:async n=>{calls.push(['detail',n]);return {id:'p'+n,musinsa_no:n,name:'Product '+n,brand_name:'Fixture',is_own:false,rank_position:2,rank_snapshot_date:'2026-10-06',final_price:50000,list_price:50000,review_count:0,ranking_best_records:[],item_seasons:[],labels:[],colors:[],sizes:[]};},fetchProductHistories:async n=>{calls.push(['history',n]);if(mode==='fail')throw Error('RPC missing');if(mode==='late')return new Promise(resolve=>{resolveA=resolve;});const r=structuredClone(weekly);r.points[1].price=null;if(mode==='allnull')for(const p of r.points)p.price=null;return parse(r);},fetchProductCategoryRanks:async()=>({rows:[],snapshot_date:''}),fetchReviews:async()=>({rows:[],total:0})};
 const hidden={__esModule:true,default:()=>null};const mocks={'@/lib/queries':queries,'@/lib/queries-me':{fetchNoteCountForEntity:async()=>0,logView:async()=>{}},'next/navigation':{useSearchParams:()=>new URLSearchParams('no='+no),useRouter:()=>({push(){}})},'next/link':{__esModule:true,default:({children})=>React.createElement('span',null,children)},'@/components/me/NoteDrawer':{...hidden,SourceNoteFallback:()=>null,useSourceNoteDrawer:()=>({noteDrawerOpen:false,setNoteDrawerOpen(){}})},'@/components/me/BookmarkToggle':hidden,'@/components/product/ProductObservationPanel':hidden,'@/components/product/ProductReviewMode':{__esModule:true,default:({children})=>children},'@/hooks/useObservationReviewState':{useObservationReviewState:()=>null},'@/components/mobile/ReviewDetailSheet':hidden,recharts:Object.fromEntries(['LineChart','Line','XAxis','YAxis','Tooltip','ResponsiveContainer','ReferenceDot'].map(k=>[k,({children,...props})=>React.createElement('fixture-'+k,props,children)]))};
 const Component=load('src/app/(app)/product/'+(mobile?'MobileProductDetailView.tsx':'page.tsx'),mocks).default;let tree;const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};const text=()=>JSON.stringify(tree.toJSON());
 try{await React.act(async()=>{tree=Renderer.create(React.createElement(Component));await flush();});assert.ok(text().includes('Product 123'));assert.ok(text().includes('이력 다시 시도'));assert.ok(!text().includes('조회 범위에 저장된 관측이 없습니다'));
 const before=calls.filter(c=>c[0]==='detail').length;mode='ready';await React.act(async()=>{tree.root.findAllByType('button').find(b=>b.children.includes('이력 다시 시도')).props.onClick();await flush();});assert.equal(calls.filter(c=>c[0]==='detail').length,before);assert.ok(text().includes('최신 진행 중인 주'));const chart=tree.root.findAllByType('fixture-LineChart');assert.equal(chart.length,2);assert.equal(chart[1].props.data[1].price,null);assert.deepEqual(chart[0].props.data.map(p=>p.date),chart[1].props.data.map(p=>p.date));assert.equal(chart[0].props.data.at(-1).date,'2026-10-06');assert.ok(tree.root.findAllByType('fixture-Line').filter(n=>n.props.dataKey==='price').every(n=>n.props.connectNulls===false));
 mode='allnull';no='555';await React.act(async()=>{tree.update(React.createElement(Component));await flush();});assert.ok(text().includes('동일 순위 관측의 유효 가격이 없습니다'));assert.ok(!text().includes(JSON.stringify('0원')));assert.equal(tree.root.findAllByType('fixture-LineChart').length,1);assert.ok(text().includes('Product 555'));mode='late';no='456';await React.act(async()=>{tree.update(React.createElement(Component));await flush();});assert.ok(!text().includes('주별 마지막 관측일'));mode='fail';no='789';await React.act(async()=>{tree.update(React.createElement(Component));await flush();});assert.ok(text().includes('Product 789'));await React.act(async()=>{resolveA(parse(weekly));await flush();});assert.ok(text().includes('이력 다시 시도'));assert.ok(!text().includes('Product 456'));assert.equal(tree.root.findAllByType('fixture-LineChart').length,0);
 }finally{if(tree)await React.act(async()=>tree.unmount());global.window=saved.window;global.document=saved.document;global.fetch=saved.fetch;}
});
